// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-jTuDufKZbi5esJS7KXqu27EXFQmKk4s',
    appId: '1:576324799617:web:c5271e6262f37a854c5180',
    messagingSenderId: '576324799617',
    projectId: 'university-schedules',
    authDomain: 'university-schedules.firebaseapp.com',
    storageBucket: 'university-schedules.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFhgWr5Gu6ZqqSujBcSH6TWmMBjenK49A',
    appId: '1:576324799617:android:3398df3f12e1f4b44c5180',
    messagingSenderId: '576324799617',
    projectId: 'university-schedules',
    storageBucket: 'university-schedules.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAepB_Z4YBOn4hSr3OB0hpdVt0jE8Pq9L4',
    appId: '1:576324799617:ios:1ea13f35afb958454c5180',
    messagingSenderId: '576324799617',
    projectId: 'university-schedules',
    storageBucket: 'university-schedules.appspot.com',
    iosClientId: '576324799617-d76j1ghhav03prona2djbd91k9gmohom.apps.googleusercontent.com',
    iosBundleId: 'com.example.instituteSchedules',
  );
}
